Nama = input("Nama\t\t\t:")
Nim = input("NIM\t\t\t:")
Kelas_paralel = input("Kelas paralel\t\t:")
birth = input("Tempat/tanggal lahir\t:")
address = input("Alamat\t\t\t:")
hobby = input("Hobby\t\t\t:")
Nohp = input("No.HP\t\t\t:")

print("Nama\t\t\t:" + Nama)
print("NIM\t\t\t:" + Nim)
print("Kelas paralel\t\t:" + Kelas_paralel)
print("Tempat/tanggal lahir\t:" + birth)
print("Alamat\t\t\t:" + address)
print("Hobby\t\t\t:" + hobby)
print("No.HP\t\t\t:" + Nohp)