print("##############################")
print("#                            #")
print("#   Muhammad Daffa Muysafa   #")
print("#       2310817110008        #")
print("#                            #")
print("##############################")